name: Dummy Status Check

on:
  pull_request:
  push:
    branches:
      - main  # Ensures it runs on pushes to main

jobs:
  dummy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Status Check
        run: echo "Passing status check"
